### PR TITLE
[no-release-notes] fix memo gen

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by PavelSafronov** [comment]
Running `go generate ./...` on this branch creates 3 changed files. I think those should be included in this PR.

**Comment by max-hoffman** [comment]
i see one import format change in `sql/analyzer/memo.og.go`. what do you see?

**Comment by max-hoffman** [comment]
note the generator is poorly isolated from the source files. i have been slowly fixing these, but currently you have to install to regen.

**Comment by PavelSafronov** [comment]
I'm seeing these changes:
image

**Pull request merged**
