### PR TITLE
sql/analyzer: Fix error not reported to caller

### PR DESCRIPTION
**Pull request by jfrabaute**
This fixes the issue #815

### CODE REVIEW

**Comment by zachmu** [comment]
Looks like this was a load-bearing skipped error

@max-hoffman can you drive this home?

**Comment by max-hoffman** [comment]
I fixed in the index filters PR and moved the invalid tests to the broken section.

**Comment by zachmu** [comment]
Specifically: the index analysis should not fail when a literal has the wrong type for its columns like this, but we shouldn't drop other errors from getIndexes

**Comment by zachmu** [comment]
> I fixed in the index filters PR and moved the invalid tests to the broken section.

This needs to be fixed ASAP. A query should never error out during analysis because of incompatible types in an equality expression.

**Comment by zachmu** [comment]
Closing this as it's been addressed in another PR

**Pull request closed without merging**
