### PR TITLE
Fix Children() function of IndexedTableAccess

### LINKED ISSUE #478: Cannot transform IndexedTableAccess nodes
The WithChildren() function of IndexedTableAccess expects an IndexAddressableTable to be passed in as the child. However, it's Children() function is simply the Children() function of it's anonymously embedded ResolvedTable, which returns 0 children. This causes errors in code that expects the output of Children() to be valid input to WithChildren(). It looks like IndexedTableAccess should have it's own Children() implementation that returns its ResolvedTable node.

### PR DESCRIPTION
**Pull request by andremarianiello**
Fix #478

### CODE REVIEW

**Comment by reltuk** [comment]
If we want to expose the ResolvedTable as a child of the IndexedTableAccess, this is probably going to require more work in the analyzer. Currently the tree walks and the `WithChildren` calls in things like filter pushdowns are seeing the child of ResolvedTable, and not seeing the ResolvedTable itself. So this change in isolation seems to cause test (and functionality) failures.

**Comment by andremarianiello** [comment]
@reltuk I was just looking at those, and what you said makes sense. I think a better solution would be to remove the Children and WithChildren methods from IndexedTableTaccess (delegating to the underlying methods from the ResolvedTable), and to stop using the WithChildren method on the IndexedTableAccess node to set the ResolvedTable, like so:

```diff
--- a/sql/analyzer/tables.go
+++ b/sql/analyzer/tables.go
@@ -189,7 +189,9 @@ func withTable(node sql.Node, table sql.Table) (sql.Node, error) {
                        if err != nil {
                                return nil, err
                        }
-                       return n.WithChildren(newRt)
+                       n2 := *n
+                       n2.ResolvedTable = newRt
+                       return &n2, nil
                default:
                        return n, nil
                }
```

What do you think about this solution? It made the sql/analyzer tests pass locally.

**Comment by reltuk** [comment]
I think that approach could be totally reasonable if it can pass tests. The asymmetry between `Children()` and `WithChildren()` currently seems wrong to me. Some of the most comprehensive tests in the project are in `//enginetests`, so it can be helpful to run those locally to vet changes.

**Comment by andremarianiello** [comment]
They all passed, so I'll push these changes.

**Review by reltuk — APPROVED** [review]
Looks great. 👍

**Comment by reltuk** [comment]
Thanks for the contribution!

**Pull request merged**
