### PR TITLE
Fix race errors with memory tables

### PR DESCRIPTION
**Pull request by alecsammon**
We use this library for running our tests. These are run with the `-race` flag - and we are seeing some errors related to concurrency and updating of the tables map.

I've added a `sync.Mutex` to all the places where this map is updated - our tests are now passing :)

### CODE REVIEW

**Comment by timsehn** [comment]
Thanks for the contribution. @zachmu is the best person to review this.

**Review by zachmu — APPROVED** [review]
No objections

**Comment by alecsammon** [comment]
Thanks @timsehn and @zachmu 

Will push a linting fix now.

**Comment by alecsammon** [comment]
Thank you!

**Pull request merged**
