### PR TITLE
Fix timestamp comparisons and add regression test

### PR DESCRIPTION
**Pull request by ryanpbrewster**
# Summary
This PR fixes another regression introduced by #1061. That PR altered the way that timestamps are represented internally (they went from `string` to `[]byte`) without updating all of the locations where the previous representation was assumed.

The particular regression this PR fixes deals with timestamp comparisons. A test like
```
CREATE TABLE mytable (t TIMESTAMP);
INSERT INTO mytable (t) VALUES ('1990-01-01'), ('2020-01-01');
SELECT COUNT(1) FROM mytable WHERE t > '2000-01-01';
```
should return `1`, but today it returns `2`.

The core issue is that the filter (e.g., `WHERE t > '2000-01-01'`) needs to compare timestamps. That comparison logic has type coercion, but the type coercion only knows how to coerce a _string_ into a timestamp, and it is now being handed a `[]byte`.

The fix here is two-fold:
1. increase the priority of timestamp type coercion so that it takes precedence over binary coercion
2. ensure that the `convertValue` function correctly converts `[]byte` into timestamps (and dates)

# Motivation
https://github.com/dolthub/go-mysql-server/issues/1139

This is not strictly speaking the same issue, but something wonky is going on with timestamps and I'd like to get to the bottom of it, and then fix it "for good".

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
@fulghum I'd like to continuing pulling this thread, if you're amenable.

**Comment by ryanpbrewster** [comment]
I managed to track down the core issue here

**Comment by fulghum** [comment]
Hey @ryanpbrewster, thank you for sending us this contribution! 🙏  I'll review today for you.

**Review by fulghum — APPROVED** [review]
Awesome work tracking this one down @ryanpbrewster! Your changes look great. I'll go ahead and merge them in to main. 

Thanks again for taking the time to debug this and send the contribution. It's extremely appreciated!! 🙏

**Pull request merged**
