### PR TITLE
fix panic of concurrent map writes, when using in memory mode

### PR DESCRIPTION
**Pull request by kom0055**
#1306 fix  panic of concurrent map writes, when using in memory mode

### CODE REVIEW

**Comment by paralin** [comment]
Doesn't this generic map type exists somewhere else already that we can import from?

**Comment by zachmu** [comment]
> Doesn't this generic map type exists somewhere else already that we can import from?

Unfortunately not, this is a gap in the standard golang libraries at the moment. Various third party packages implement one but it's easy to enough to write your own like this.

**Comment by zachmu** [comment]
Thanks for the contribution. This PR looks fine, but please understand that this by itself doesn't make the in-memory implementation thread-safe. There's still no transaction support or row locking, which is necessary for true concurrency. This may work for some limited use cases but it's not a general solution to concurrency.

**Comment by zachmu** [comment]
I had to merge main to correct a testing issue on our end. New PR is here:

https://github.com/dolthub/go-mysql-server/pull/2185

**Pull request closed without merging**
