### PR TITLE
fix a bug that will change time zone

### PR DESCRIPTION
**Pull request by xiazemin**
there is a bug that will change timestame from time_zone local to utc

### CODE REVIEW

**Comment by xiazemin** [comment]
I have fixed the testing，please review

**Comment by xiazemin** [comment]
Is there anything I need to do?

**Comment by xiazemin** [comment]
> Hey @xiazemin, thank you for the contribution and sorry for the slow response.
> 
> Can you please describe the exact bug that you found? A little more context will help us review. For any contribution, we also need to have updated tests that cover the fix. I took a quick look at the code changes, but wasn't sure using `time.Local` is the right choice here. I haven't dug into all the details, but it seems like we'd want to honor the MySQL timezone system variables and make sure we're using the right connection timezone.

   Mysql server will not change the time zone of  UTC_TIMESTAMP() or values in DATE, TIME, or DATETIME columns.  
 ```
The session time zone setting does not affect values displayed by functions such as UTC_TIMESTAMP() or values in DATE, TIME, or DATETIME columns. Nor are values in those data types stored in UTC; the time zone applies for them only when converting from TIMESTAMP values. If you want locale-specific arithmetic for DATE, TIME, or DATETIME values, convert them to UTC, perform the arithmetic, and then convert back.
```
https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html

But when I use  go-mysql-server, If my TZ is Asia/ShangHai , when I store a DATETIME column like '2023-05-09 00:09:00' with standard mysql-cli client ,where I query with the same session  I will get  '2023-05-09 00:01:00' . The reason is that mysql-server will not parse DATETIME string, but go-mysql-server will parse it with time-zone UTC.

**Comment by xiazemin** [comment]
> Hey @xiazemin, thank you for the contribution and sorry for the slow response.
> 
> Can you please describe the exact bug that you found? A little more context will help us review. For any contribution, we also need to have updated tests that cover the fix. I took a quick look at the code changes, but wasn't sure using `time.Local` is the right choice here. I haven't dug into all the details, but it seems like we'd want to honor the MySQL timezone system variables and make sure we're using the right connection timezone.



there is a example:

```
mysql> create table test (  `sale_end` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '停售时间');
Query OK, 0 rows affected (0.00 sec)

mysql> insert into test (sale_end) values('2023-05-09 09:00:00 +0800 CST');
Query OK, 1 row affected (0.00 sec)

mysql> select * from test;
+---------------------+
| sale_end            |
+---------------------+
| 2023-05-09 01:00:00 |
+---------------------+
1 row in set (0.00 sec)
```

If we use '2023-05-09 09:00:00' without time_zone info,the result is right

**Comment by xiazemin** [comment]
> details

Your mysql-cli time zone is not right.

mysql:
```
select version();
+-----------+
| version() |
+-----------+
| 8.0.28    |
+-----------+
1 row in set (0.00 sec)

mysql>  set time_zone='+08:00';
Query OK, 0 rows affected (0.00 sec)

mysql> insert into test (sale_end) values(now());
Query OK, 1 row affected (0.01 sec)

mysql>  select * from test;
+---------------------+
| sale_end            |
+---------------------+
| 2023-05-10 08:34:26 |
+---------------------+
1 row in set (0.00 sec)
```

dolthub:

```
select version();
+-----------+
| version() |
+-----------+
| 8.0.11    |
+-----------+
1 row in set (0.00 sec)

mysql>  set time_zone='+08:00';
Query OK, 1 row affected (0.00 sec)

mysql>  insert into test (sale_end) values(now());
Query OK, 1 row affected (0.01 sec)

mysql>  select * from test;
+----------------------------+
| sale_end                   |
+----------------------------+
| 2023-05-10 00:34:54.829375 |
+----------------------------+
1 row in set (0.00 sec)
```

Is this clear?

**Comment by xiazemin** [comment]
> insert into test (sale_end) values('2023-05-09 09:00:00 +0800 CST');

example2:

```


mysql> set time_zone='+08:00';
Query OK, 1 row affected (0.00 sec)

mysql> insert into test (sale_end) values('2023-05-09 09:00:00+08:00');
Query OK, 1 row affected (0.01 sec)

mysql> select * from test;
+---------------------+
| sale_end            |
+---------------------+
| 2023-05-09 09:00:00 |
+---------------------+
1 row in set (0.00 sec)


set time_zone='+00:00';
Query OK, 0 rows affected (0.00 sec)
mysql> insert into test (sale_end) values('2023-05-09 09:00:00+08:00');
Query OK, 1 row affected (0.00 sec)
select * from test;
+---------------------+
| sale_end            |
+---------------------+
| 2023-05-09 01:00:00 |
+---------------------+
1 row in set (0.00 sec)
```

dolthub:
```

mysql> set time_zone='+08:00';
Query OK, 1 row affected (0.00 sec)

mysql> insert into test (sale_end) values('2023-05-09 09:00:00 +0800 CST');
Query OK, 1 row affected (0.01 sec)

mysql> select * from test;
+---------------------+
| sale_end            |
+---------------------+
| 2023-05-09 01:00:00 |
+---------------------+
1 row in set (0.00 sec)

 set time_zone='+00:00';
Query OK, 1 row affected (0.00 sec)

mysql> insert into test (sale_end) values('2023-05-09 09:00:00 +0800 CST');
Query OK, 1 row affected (0.00 sec)

mysql> select * from test;
+---------------------+
| sale_end            |
+---------------------+
| 2023-05-09 01:00:00 |
+---------------------+
1 row in set (0.00 sec)


```

**Comment by fulghum** [comment]
Those two repro examples are very helpful. Thank you for writing them up – that makes the issue much, much clearer. (There are many edge cases left for correct timezone handling, so knowing exactly which ones you need is really important.)

For the first example you shared, with the use of `NOW()`, I've got PR https://github.com/dolthub/go-mysql-server/pull/1767 handles what you want here – it makes the `NOW()` function respect the `@@session.time_zone` variable. I tested with my local dev build and was able to reproduce the same behavior as MySQL, like you documented in the first repro example. 

The second example is a little more interesting... it requires correctly handling datetime and timestamp literals that contain explicit timezone information. I've got a prototype working in my local workspace and the logic isn't that hard, but it requires getting access to the `@@time_zone` session variable, and that code doesn't currently have a `sql.Context` reference, so it involves quite a bit of plumbing to add that additional function parameter, updating an interface, and the many implementations. I'll take another pass at cleaning up that PR tomorrow.

**Comment by timsehn** [comment]
I'm closing this as we are not going to merge it. We tried to merge a timezone change to fix your underlying issue and it broke the Java client. It's on our list of things to fix.

**Pull request closed without merging**
