### PR TITLE
Add Locate SQL function

### PR DESCRIPTION
**Pull request by MathiasGr**
Add Locate SQL function.

I'm trying to achieve minimum compatibility with Metabase's MySQL connector, and it requires a couple new functions, so you'll see a few more PRs from me.

Reference: https://www.w3schools.com/sql/func_mysql_locate.asp

### CODE REVIEW

**Review by zachmu — COMMENTED** [review]
This looks good, thanks for the contribution!

Please add engine tests in queries.go here:

https://github.com/dolthub/go-mysql-server/blob/main/enginetest/queries.go

Make sure you have at least one test case with a column expression being used as a function argument.

Assuming that works I'll merge this.

Thank again for the contribution.

**Comment by zachmu** [comment]
Hi @MathiasGr,

Sorry for the delay, it's a time of the year a lot of us are out of the office.

Thanks a ton for this and your other contributions, we really appreciate it.

For this and the others, please add engine tests as explained in the review comment, and we'll get them merged.

Thanks again,

Zach

**Comment by MathiasGr** [comment]
> This looks good, thanks for the contribution!
> 
> Please add engine tests in queries.go here:
> 
> https://github.com/dolthub/go-mysql-server/blob/main/enginetest/queries.go
> 
> Make sure you have at least one test case with a column expression being used as a function argument.
> 
> Assuming that works I'll merge this.
> 
> Thank again for the contribution.

OK I just did, let me know if that matches your expectations.

**Review by zachmu — APPROVED** [review]

**Comment by zachmu** [comment]
Perfect, thanks.

**Pull request merged**
