### PR TITLE
Add extra filters to AntiJoin to guarentee correct behavior around NULLs.

### PR DESCRIPTION
**Pull request by nicktobey**
This is a correctness fix: generating AntiJoins is not currently equivalent to MySql if either column being used in the `not in` expression contains NULL.

This will break a lot of regression tests. If this doesn't break Turbine's tests, we should submit this while we work on a fix.

### CODE REVIEW

**Comment by nicktobey** [comment]
Not applying AntiJoin here fixes the regression tests that I added... but it breaks the IntegrationQueryPlans, which are important for asserting a specific performance improvement that we promised Turbine.

I'm looking into a fix that will hopefully make this whole thing moot.

**Comment by nicktobey** [comment]
Alright, this should fix [the issue](https://github.com/dolthub/dolt/issues/5954), with a couple of consequences that need to be addressed.

The `IntegrationQueryPlan` tests are generating slightly different plans from before, and I lack the experience to gauge whether they're correct. I'd love for @JCOR11599 or @max-hoffman to give me their input here.

The added filters are also potentially inefficient, but in a way that a later optimization can probably account for (I'm just not sure if it currently does.) One of the filters only matches on the left table, which means that if we naively iterate over the `existsIter`, then for each row on the left table, we will check that filter for each row on the right table, even though we should only have to check it once.

**Review by max-hoffman — CHANGES_REQUESTED** [review]
I am happy with the investigative work, still not happy with the exchange of trade-offs given the rarity of the edge case my preferred solution misses:

```sql
select 1 where 1 not in (select 1 union select null);
Empty set (0.01 sec)
```
As a reminder MySQL expects empty results, but we ignore the null and return the matching rows when this ANTI_JOIN is converted to HASH_LEFT_JOIN.

Summarization of thoughts:
- This is directionally right, we have a correctness gap with MySQL.
- The specific queries that fail the correctness gap are rare and fail in a way that is obvious to end users if they expect the MySQL behavior (i.e. we return the matches when they expect NULL to nullify the antiJoin).
- It is easy for us to provide workarounds if users balk.
- `existsIter` nullability checks fix most cases, but I've confirmed there is still a correctness gap if the ANTI_JOIN gets converted to a HASH_LEFT_JOIN.
- The correct way to do this is to add functional dependency properties that aggressively track column nullability, which I think will be backwards-compatible for customer queries.
- In the meantime we can't revert customers happy with the current behavior back to O(n)-memory joins.
- One medium term option is to inject the additional filter at the ANTI_JOIN->LEFT_JOIN stage, or add joins to the tree that nullify ANTI_JOINs if either relation contains a NULL. I haven't tested, and these might work.
- We have a lot of other work that is higher-priority, I would prefer we time box this, document our findings in the issue and in tests, and move to customer-requested features and performance work. If we have a customer that needs this behavior and won't budge on small query rewrites, we target the ANTI_JOIN -> LEFT_JOIN optimization before doing anything to IN_SUBQUERY->ANTI_JOIN.

**Comment by nicktobey** [comment]
Okay, I have something working now.

My thoughts:

- This is not the highest priority and we should avoid spending more time on this.
- That said the MySql correctness issue here, although rare, is troubling because it silently does the wrong this in a way that is _hopefully_ obvious to diagnose if it happens to a customer, but we shouldn't bank on that.
- Injecting an additional filter at the ANTI_JOIN->LEFT_JOIN stage isn't possible. (Imagine adding a row to the right table where the column being joined on is NULL. That row can never match, which means it can never affect the joined table, and adding an extra filter can't change that.)
- The only real solution is to add a flag to that the iterator uses to bail on a left table row if the result of a comparison is NULL.
- I opted to encode this flag in the `JoinType` because it's harder to accidentally drop this information as we continue to modify the tree. (It also means we don't have to pass a new parameter around everywhere.) There is now a new type `JoinTypeLeftOuterExcludeNulls`. Feel free to critique the name.
- I also added the `JoinTypeLeftOuterHashExcludeNulls` physical plan. I didn't add equivalents for Merge and Lookup yet (apparently none of our tests for this behavior generate Merge or Lookup plans.) I can of course add them before submitting.
- It's really starting to look like an enum isn't the best structure for `JoinType`. We're starting to see a combinatorial explosion of properties.

**Review by max-hoffman — APPROVED** [review]
lgtm, one recommended test change from last week. I'm maybe not against moving some attributes to the join structs. You could add tests to `query_plans.go` if your goal was tests that print the null exclusion property. There are other unique naming options also, `LeftAntiJoin`, `LeftAntiHashJoin`,... I'm fine w/ this as is. I expect the execution logic to accumulate complexity until its rewritten and simplified for perf at a later point.

**Comment by timsehn** [comment]
What are we waiting for here?

**Pull request merged**
