### PR TITLE
 Trim spaces and empty statements to the right in planbuilder.Parse 

### PR DESCRIPTION
**Pull request by reusee**

### CODE REVIEW

**Comment by timsehn** [comment]
Thanks for the contribiution. @fulghum or @zachmu will review it today.

At first glance, a why in the PR description and maybe a test of this new behavior would be ncie.

**Comment by zachmu** [comment]
This looks fine to me but Max should take a look to see if I'm missing something obvious.

Main thing is that this should be symmetric between both the places in the code base we parse, and this only hits one.

**Comment by max-hoffman** [comment]
This edits an in-progress rewrite with only partial testing coverage. This PR should copy the changes to the equivalent lines in `sql/parse/parse.go`. If those changes pass tests then OK with me.

**Comment by reusee** [comment]
> This edits an in-progress rewrite with only partial testing coverage. This PR should copy the changes to the equivalent lines in `sql/parse/parse.go`. If those changes pass tests then OK with me.

Done. But some test cases in sql/parse/parse_test.go need updates.

**Pull request merged**
