### PR TITLE
Use comparandExprs as keyExprs for indexed joins

### LINKED ISSUE #479: Cannot use expression index in indexed join
I have a table where I want to index on not just a column, but an expression, e.g.  `JSON_EXTRACT(payload, '$.id')`. The docs for sql.Index say this is allowed

```
    // Expressions returns the indexed expressions. If the result is more than
    // one expression, it means the index has multiple columns indexed. If it's
    // just one, it means it may be an expression or a column.
```

However, it appears that the indexed join transform rule expects these to be only columns

```
// createIndexLookupKeyExpression returns a slice of expressions to be used when evaluating the context row given to the
// RowIter method of an IndexedTableAccess node. Column expressions must match the declared column order of the index.
func createIndexLookupKeyExpression(ctx *sql.Context, ji *joinIndex, tableAliases TableAliases) []sql.Expression {

        keyExprs := make([]sql.Expression, len(ji.index.Expressions()))
IndexExpressions:
        for i, idxExpr := range ji.index.Expressions() {
                for j, col := range ji.cols {
                        if idxExpr == normalizeExpression(ctx, tableAliases, col).String() {
                                keyExprs[i] = ji.comparandExprs[j]
                                continue IndexExpressions
                        }
                }

                // If we finished this loop, we didn't find a column of the index in the join expression.
                // This should be impossible.
                return nil
        }

        return keyExprs
}
```

How can I use an expression index in an indexed join?

### PR DESCRIPTION
**Pull request by andremarianiello**
Fix #479

### CODE REVIEW

**Comment by andremarianiello** [comment]
I don't fully understand why the code deleted in the PR was written the way it was in the first place. The necessary expressions (in my understanding) seem to already have been collected in the join index. All I had to do was use them. This doesn't break any tests so I assume this is a safe change, but I could be mistaken. If anyone sees anyone reason why it shouldn't be done this way, please let me know.

**Comment by andremarianiello** [comment]
Since this does seem to be breaking tests I will take a look at the failures when I get a chance.

**Comment by zachmu** [comment]
The reason this doesn't work is that you have to match the order of the comparands to the order of the index expressions, that's what the loop is doing

**Comment by andremarianiello** [comment]
Alright, I'll take another look at that loop.

**Pull request closed without merging**
