### PR TITLE
Skip process tracking when prepreparing queries

### PR DESCRIPTION
**Pull request by fulghum**
When we prepare a statement, the `QueryProcess` node we create is bound to the current context's PID. This is not the same PID as the context that will execute a statement created from that template, which results in ProcessList metadata not being properly cleaned up after a query has finished processing. 

Fixes: https://github.com/dolthub/dolt/issues/4601

I couldn't find a great way to test this in the GMS package, but I'm working on a test in dolt that I'll link to shortly.

### CODE REVIEW

**Comment by max-hoffman** [comment]
Would skipping `trackProcess` in `prePrepareRuleSelector`, and applying `trackProcess` in `postPrepareRuleSelector` have the same effect?

**Comment by fulghum** [comment]
> Would skipping `trackProcess` in `prePrepareRuleSelector`, and applying `trackProcess` in `postPrepareRuleSelector` have the same effect?

Thanks for the nice tip! I hadn't found those selectors yet. Just tested manually and confirmed this works. I like this better, too, since we don't have to copy around that dispose function.

**Comment by fulghum** [comment]
The cleaner fix ended up exposing another bug where `TransactionCommittingNode.WithChildren()` wasn't making a copy of itself, which caused the analyzer to not rerun a batch of rules, which caused a statement to not get fully resolved and fail tests. That's fixed up now, too, and I'll make a quick grep audit of `WithChildren()` methods to see if we have similar bugs hiding around, too. 

@max-hoffman – this one is ready for another look from you now that all tests are passing!

**Review by max-hoffman — APPROVED** [review]
LGTM! A test to maintain this behavior would be nice, even if it is a unit test that manually creates a node, runs pre-prepare with one ID and post-prepare with a second ID. Just to make sure no one goes in and reverts this.

**Comment by fulghum** [comment]
> A test to maintain this behavior would be nice, even if it is a unit test that manually creates a node, runs pre-prepare with one ID and post-prepare with a second ID. Just to make sure no one goes in and reverts this.

Good suggestion. I spent some time yesterday digging through the analyzer's unit tests a little more and found a good spot to test this. I'll clean that test up and get this change merged to main in few moments.

**Pull request merged**
