### PR TITLE
Fix package network for navicat

### PR DESCRIPTION
**Pull request by lxShaDoWxl**
#1567

### CODE REVIEW

**Comment by fulghum** [comment]
Thanks for the contribution @lxShaDoWxl! 🙏  The field metadata change makes sense so far, but I'd like to test some of that a little more – we're in the process of changing some of our tests to ensure they run through the full end-to-end codepath, including wire serialization, and this seems like a great change to run through that enhanced test suite. I approved the CI tests and see that some of the unit tests failed, but on first look, they may just need to be updated for the new values being included now. 

I'm not sure I understand the change to `sql/column.go` yet. I see your comment in the related issue about `reflect.DeepEqual(c.Default, c2.Default);` always being false, but I don't think I'm seeing what you're seeing yet. It seems like a valid check to compare the two `Default` members, but let me know if I just missed something when I took a quick look there and I'll be happy to take a closer look.

**Comment by lxShaDoWxl** [comment]
@fulghum Привет! Вот как я увидел проблему с Default
Создал таблицу
```sql
CREATE TABLE `test`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT "",
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;
```
запустил debug и вот что там увидел
Снимок экрана от 2023-08-22 16-13-01

**Comment by fulghum** [comment]
Thanks for the extra details and screenshot @lxShaDoWxl. We do rely on that column default check in other places, so I'm pretty confident we want to keep that in the equals check. I have seen other issues where a column's default value just isn't properly loaded/resolved yet though, so that could be what you're seeing. Was there a query you were running that was giving you an error or the wrong results?

Would you be willing to help update the failing unit tests, too? I quickly checked a few failures and it looks like they are coming from the new field metadata being populated, and the tests just aren't yet expecting those values to be filled in.

**Comment by lxShaDoWxl** [comment]
актуализировал свою ветку main и вернул обратно проверку Default, режим только чтение исчез и можно нормально редактировать. 😳
Обновил тесты

**Comment by fulghum** [comment]
Nice! Thanks for updating the tests and reverting the column default change. Glad to hear things are working smoothly with Navicat with this configuration now. 

Since this change affects the data we send at the wire protocol level, I'd like to run this with some of our test suite using a new test harness we just created that tests the wire serialization better. I'll try to get those tests running later today, but it may end up going into next week. 

Thank you for working with us on this contribution! 🙏

**Comment by timsehn** [comment]
This has been dead for a while. Closing. Reopen if you want.

**Pull request closed without merging**
