### PR TITLE
Bug fix for table alias resolution

### PR DESCRIPTION
**Pull request by fulghum**
Fixes: https://github.com/dolthub/dolt/issues/4183

### CODE REVIEW

**Review by max-hoffman — COMMENTED** [review]
I think we need to differentiate tables and aliases that have different casings. For example the only column pruned below should be `A.s`:
```sql
mysql> select a.* from mytable a join mytable A on a.i = A.i;
+------+------------+
| i    | s          |
+------+------------+
|    1 | first row  |
|    2 | second row |
|    3 | third row  |
+------+------------+
```
So we should keep the `strings.ToLower` for columns, but maybe axe the lines where I lowercased table names?

As a final req, it is helpful to add a plan to `QueryPlans` whenever we add an execution test. If you add a query stub to the plans, `TestWriteQueryPlans` will generate a new set of plans with the plans filled in.

**Comment by fulghum** [comment]
Thanks Max. I tried that query on MySQL, but it won't execute because of the ambiguous reference:
`ERROR 1066 (42000): Not unique table/alias: 'A'`

I confirmed that Dolt returns the same error response. 

I also tried another case where there is a table and a table alias with the same name, but different case. Both Dolt and MySQL have the same behavior and return the same error as above. 
```
> select * from a left join mytable A on (a.x = A.x);
ERROR 1066 (42000): Not unique table/alias: 'A'
```

Since those cases are disallowed, I think we're doing the right thing by converting table and table aliases to lowercase. Let me know if you see something I don't though! 

Thanks for the tip on `TestWriteQueryPlans`! I'll get that update in in just a moment.

**Comment by timsehn** [comment]
Maybe codify these errors in engine tests since they are contentious?

**Comment by max-hoffman** [comment]
The query I shared returned in mysql `8.0.27`, I wonder if they have different aliasing rules per release and which one we should align with?
```sql
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.27    |
+-----------+
```

**Comment by max-hoffman** [comment]
@fulghum pointed out that MySQL `8.0.29` is more restrictive about aliases, so we should probably align with the more recent release!

**Comment by fulghum** [comment]
I added an error query test for case-insensitive duplicate alias. We had some similar tests for that same error message, but not one for a case-insensitive duplicate, so that was a good call. 

@max-hoffman – let me know if you have any other recommendations before approving.

**Review by max-hoffman — APPROVED** [review]
LGTM, thanks for fixing!

**Pull request merged**
