### PR TITLE
Add support for passing query to QueryCompleted.

### PR DESCRIPTION
**Pull request by joel-rieke**

### CODE REVIEW

**Comment by timsehn** [comment]
@joel-rieke you gonna keep working on this one?

**Comment by joel-rieke** [comment]
I think it's done.  It's just a question of whether anyone wants it.

**Comment by timsehn** [comment]
Alright, take it out of draft and @fulghum will review :-)

**Comment by timsehn** [comment]
And maybe add your goal in the description? I can't figure out from the code what you're trying to accomplish. I'm not an expert so maybe it's obvious to @fulghum or @zachmu who work on this code all the time.

**Pull request closed without merging**
