### PR TITLE
Support decimal literals.

### PR DESCRIPTION
**Pull request by PavelSafronov**
Fixes https://github.com/dolthub/dolt/issues/5068

### CODE REVIEW

**Review by jennifersp — APPROVED** [review]
LGTM! It would be good to add the previously failing test(this value used in a table) from the issue.

**Comment by PavelSafronov** [comment]
> LGTM! It would be good to add the previously failing test(this value used in a table) from the issue.

Without the parse.go changes, the added queries will generate errors:
```
=== RUN   TestQueriesSimple/SELECT_809826404100301269648758758005707100;
    evaluation.go:284: 
        	Error Trace:	evaluation.go:284
        	Error:      	Received unexpected error:
        	            	strconv.ParseUint: parsing "809826404100301269648758758005707100": value out of range
        	Test:       	TestQueriesSimple/SELECT_809826404100301269648758758005707100;
        	Messages:   	Unexpected error for query SELECT 809826404100301269648758758005707100;: strconv.ParseUint: parsing "809826404100301269648758758005707100": value out of range
    --- FAIL: TestQueriesSimple/SELECT_809826404100301269648758758005707100; (0.00s)
```

@jennifersp  Is this what you are referring to? Or is there another place to add these values?

**Comment by jennifersp** [comment]
@PavelSafronov Sorry it's not clear, I meant the repro in the issue https://github.com/dolthub/dolt/issues/5068 can be added as a test so that we have are testing this value in a table form as well.

**Review by fulghum — APPROVED** [review]
Great fix! 🙌

**Pull request merged**
