### PR TITLE
prep counter with failure

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Review by zachmu — COMMENTED** [review]
I like the sentiment of making sure that all tests pass with prepared statements, but I think this is going to cause as much confusion as it catches bugs. The thing with the magic number especially -- people are just going to change it instead of adding new prepared tests.

A better way of assuring prepared coverage would be a separate harness combined with code gen, with a manually updated list of test methods that can't be used with the prepared harness.

**Comment by max-hoffman** [comment]
@zachmu If i codegen it, then I have to do it separately for `memory_engine_test.go` and `dolt_engine_test.go`, which is probably 2-3 days of automation. You don't think this is a useful stop-gap until we have a bit of time to rework testing?

**Comment by zachmu** [comment]
I would hold off on these checks until we can do it a better way

**Comment by timsehn** [comment]
Should we just close this?

**Comment by max-hoffman** [comment]
Fine w me, the checks in the Dolt repo have worked well enough on their own.

**Pull request closed without merging**
