### PR TITLE
Render enum/set variables as strings after they are set

### PR DESCRIPTION
**Pull request by adjeiv**
Fixes https://github.com/dolthub/dolt/issues/6370
Ensure that when getting all session variables, if any of them is of an enum/set type, we convert them back to their string value. The SET command would amend the value in the session variables map to its numerical representation, which we need to translate back.

### CODE REVIEW

**Comment by adjeiv** [comment]
Note - `system_variables.go` may have similar behaviour, as the code there also doesn't perform this conversion back to string

**Comment by timsehn** [comment]
Thanks for the PR. @fulghum will look at this today.

**Comment by fulghum** [comment]
> Note - `system_variables.go` may have similar behaviour, as the code there also doesn't perform this conversion back to string

Ahh... good callout. Looks like `SET @@GLOBAL.SQL_MODE='ONLY_FULL_GROUP_BY'; SHOW GLOBAL VARIABLES LIKE '%sql_mode%';` has the same issue, and a similar fix could be applied. I think it's fine to handle that fix separately from this session variable fix. No pressure of course, but if you're feeling up for it, that would be another really appreciated contribution! 😁 

I also quickly tested with enums, but I wasn't able to reproduce this issue with them.

**Review by fulghum — APPROVED** [review]
Thank you for the contribution @adjeiv! 🙏 Very cool to see you jump into the codebase and contribute this fix! ⚡️

Let us know if you need any help looking for other good issues to dig into!

**Comment by bpf120** [comment]
Hi @adjeiv, Thanks for contributing. Do you have a Dolt use case you are working on too? We'd love to hear about it. :)

Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.

**Pull request merged**
